name: Build on Windows

on:
  push:
    tags:
      - v[0-9]+.*
    branches: [ develop, main ]
jobs:
  build-and-artifact:
    
    name: ${{ matrix.os }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        configuration: [ debug, release ]
        os: [ windows-latest ]
        arch: [x64]
        BUILD_SHARED_LIBS: [OFF]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set output dir
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=$([[ ${{matrix.BUILD_SHARED_LIBS}} == OFF ]] && echo '${{ github.workspace }}/build/static' || echo '${{ github.workspace }}/build/shared')" >> $GITHUB_OUTPUT

      - name: Configure CMake
        run : |
          cmake -B ${{ steps.strings.outputs.build-output-dir }} -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DBUILD_SHARED_LIBS=${{ matrix.BUILD_SHARED_LIBS }}

      - name: Build
        run : |
          cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.configuration }}

      - name: Pack
        run : |
          mkdir ${{ github.workspace }}/${{ matrix.configuration }}
          mkdir ${{ github.workspace }}/${{ matrix.configuration }}/include
          mv ${{ steps.strings.outputs.build-output-dir }}/src/${{ matrix.configuration }}/libok-gloox.* ${{ github.workspace }}/${{ matrix.configuration }}
          cp ${{ github.workspace }}/src/*.h ${{ github.workspace }}/${{ matrix.configuration }}/include

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: libgloox-win-${{ matrix.arch }}-${{ matrix.configuration }}
          path: |
            ${{ github.workspace }}/${{ matrix.configuration }}/include
            ${{ github.workspace }}/${{ matrix.configuration }}/ok-gloox.*

  release:
    needs: build-and-artifact
    runs-on: windows-latest
    env:
      IMAGE_TAG: ${{ github.event.ref_name }}
    strategy:
      matrix:
        arch: [ x64 ]
        configuration: [ debug, release ]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3

      - name: Set TAG to 'latest' if no tag is found
        shell: bash
        run: |
          if [[ "$IMAGE_TAG" != v* ]]; then
            echo "Setting IMAGE_TAG to latest"
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          path: libgloox-linux-${{ matrix.arch }}-${{ matrix.configuration }}
          filename: libgloox-win-${{ matrix.arch }}-${{ matrix.configuration }}.zip

      - name: Upload
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            libgloox-linux-${{ matrix.arch }}-${{ matrix.configuration }}-${{env.IMAGE_TAG}}.zip
